name: simple_weight_tracker
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-171.0.dev <4.0.0"

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  # Dependency Injection (DI)
  get_it: ^7.6.0
  injectable: ^2.1.2

  # Functional programming (FP)
  dartz: ^0.10.1

  # Routing
  auto_route: ^7.7.0

  # Riverpod
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6

  # Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Utils
  intl: ^0.18.0
  flutter_hooks: ^0.19.0

  # Json
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  very_good_analysis: ^5.0.0+1
  riverpod_generator: ^2.2.3
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
